// Build the recipe LIBRARY consumed by the redesigned Recipes page: pull published recipes
// (CURATED + COMMUNITY) from the DB with their computed nutrition + ingredients, classify each
// into meal-type tabs (breakfast/lunch/dinner/snack) + dessert, flag sugar-free, and emit
// src/data/recipeLibrary.js. Re-run after loading new recipes.
import pg from "pg";
import { readFileSync, writeFileSync } from "fs";
import { classify, isVeg, isSugarFree, requiredFoodsFor } from "./recipe_classify.mjs";

const url = readFileSync(new URL("./.db_url", import.meta.url), "utf8").trim();

const c = new pg.Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();

const { rows } = await c.query(`
  select r.id, r.slug, r.source_ref, r.name, r.servings, r.tagline, r.source_id, r.method,
         rn.energy_kcal, rn.protein_g, rn.fat_g, rn.carb_avail_g, rn.fibre_g, rn.flags,
         coalesce(array_agg(ri.raw_text order by ri.position) filter (where ri.raw_text is not null), '{}') as ingredients
  from recipes r
  left join recipe_nutrition rn on rn.recipe_id = r.id and rn.per = 'serving'
  left join recipe_ingredients ri on ri.recipe_id = r.id
  where r.status = 'published' and r.source_id in ('CURATED','COMMUNITY')
  group by r.id, r.source_ref, rn.energy_kcal, rn.protein_g, rn.fat_g, rn.carb_avail_g, rn.fibre_g, rn.flags
  order by r.source_id, r.name
`);

const num = v => (Number.isFinite(Number(v)) ? Number(v) : 0);
const lib = rows.map(r => {
  const ingredients = r.ingredients || [];
  const { mealTypes, dessert } = classify(r.name, ingredients, num(r.energy_kcal));
  return {
    id: (r.source_ref && r.source_ref.trim()) ? r.source_ref.trim() : r.slug,   // CURATED keeps its original id so existing favourites still match
    name: r.name,
    source: r.source_id,
    tagline: r.tagline || "",
    tags: r.tagline ? r.tagline.split(/,\s*/).filter(Boolean).slice(0, 3) : [],
    requiredSafeFoods: [],
    servings: num(r.servings) || 1,
    kcal: Math.round(num(r.energy_kcal)),
    macros: { protein: Math.round(num(r.protein_g)), fat: Math.round(num(r.fat_g)), carbs: Math.round(num(r.carb_avail_g)), fibre: Math.round(num(r.fibre_g)) },
    ingredients: ingredients.map(name => ({ name })),
    method: r.method && !/pending/i.test(r.method) ? r.method : "",
    category: dessert ? "dessert" : "meal",
    mealTypes,
    requiredFoods: requiredFoodsFor(ingredients),
    veg: isVeg(r.name, ingredients),
    sugarFree: isSugarFree(r.name, ingredients),
    flags: r.flags || [],
  };
});

const counts = { breakfast: 0, mains: 0, snack: 0, dessert: 0, veg: 0, nonveg: 0 };
for (const r of lib) r.veg ? counts.veg++ : counts.nonveg++;
for (const r of lib) for (const m of r.mealTypes) counts[m] = (counts[m] || 0) + 1;

const out = `// AUTO-GENERATED by pipeline/build_recipe_library.mjs — do not edit by hand.
// Published recipes (curated + community) with DB-computed nutrition, classified for the
// recipes-page tabs. ${lib.length} recipes.
export const RECIPE_LIBRARY = ${JSON.stringify(lib, null, 1)};
`;
writeFileSync(new URL("../src/data/recipeLibrary.js", import.meta.url), out);
console.log(`Wrote ${lib.length} recipes -> src/data/recipeLibrary.js`);
console.log("tab counts:", counts, "| sugar-free desserts:", lib.filter(r => r.category === "dessert" && r.sugarFree).length, "of", counts.dessert);
await c.end();
