#!/usr/bin/env python3
"""Transform USDA FoodData Central (SR Legacy + Foundation, public domain) into the
nutrition schema. USDA ships relational CSVs, so we join food + food_nutrient + nutrient.

USDA amounts are per 100g edible portion (matches our basis). Energy stored as both
kcal (nutrient 1008) and kJ (1062). Emits pipeline/out/usda_ingredients.sql and maps
the app foods IFCT could not cover (butter, curd, oats, cheese, …).
"""
import csv, os, re, sys

csv.field_size_limit(10_000_000)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FOODS_JS = os.path.join(ROOT, "src/data/foods.js")
OUT_SQL  = os.path.join(ROOT, "pipeline/out/usda_ingredients.sql")
OUT_RPT  = os.path.join(ROOT, "pipeline/out/usda_coverage.md")

DATASETS = [  # (dir, source_id, data_type filter)
    ("/tmp/ifct_check/usda_s/FoodData_Central_sr_legacy_food_csv_2018-04", "USDA-SR", "sr_legacy_food"),
    ("/tmp/ifct_check/usda_f/FoodData_Central_foundation_food_csv_2026-04-30", "USDA-FNDF", "foundation_food"),
]

# app foods IFCT left unmatched -> USDA description keyword. The picker prefers the
# SHORTEST description containing the keyword (generic beats branded) that has kcal.
USDA_TARGETS = {
    "butter": "butter, salted", "buttermilk": "buttermilk", "curd": "yogurt, plain, whole",
    "cheese": "cheese, cheddar", "cream / malai": "cream, fluid, heavy", "greek yogurt": "yogurt, greek, plain, whole",
    "oats": "oats", "sesame seeds": "seeds, sesame seeds, whole, dried", "olive oil": "oil, olive, salad or cooking",
    "sugar": "sugars, granulated", "honey": "honey", "watermelon": "watermelon, raw",
    "soya chunks": "soy protein isolate", "soy sauce": "soy sauce made from soy and wheat",
    "bread": "bread, white, commercially prepared", "pasta": "pasta, dry, enriched",
    "noodles": "noodles, egg, dry", "vinegar": "vinegar, distilled",
    "corn / sweet corn": "corn, sweet, yellow, raw", "grilled chicken": "chicken, broilers or fryers, breast",
}


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def load_app_foods():
    txt = open(FOODS_JS, encoding="utf-8").read()
    pat = re.compile(r'\{\s*id:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*group:\s*"([^"]+)"')
    return [{"id": i, "name": n, "group": g} for i, n, g in pat.findall(txt)]


def macro_ids(nutrient_csv):
    """Resolve the FDC nutrient_ids for the 6 macros by (name, unit)."""
    want = {}
    for r in csv.DictReader(open(nutrient_csv, encoding="utf-8")):
        nm, unit = r["name"], r["unit_name"]
        if nm == "Energy" and unit == "KCAL": want["kcal"] = r["id"]
        elif nm == "Energy" and unit == "kJ": want["kj"] = r["id"]
        elif nm == "Protein": want["protein"] = r["id"]
        elif nm == "Total lipid (fat)": want["fat"] = r["id"]
        elif nm == "Carbohydrate, by difference": want["carb"] = r["id"]
        elif nm == "Fiber, total dietary": want["fibre"] = r["id"]
        elif nm == "Water": want["water"] = r["id"]
    return want


def load_dataset(d, data_type):
    cats = {}
    cat_path = os.path.join(d, "food_category.csv")
    if os.path.exists(cat_path):
        for r in csv.DictReader(open(cat_path, encoding="utf-8")):
            cats[r["id"]] = r["description"]
    foods = {}
    for r in csv.DictReader(open(os.path.join(d, "food.csv"), encoding="utf-8")):
        if r["data_type"] != data_type:
            continue
        foods[r["fdc_id"]] = {"desc": r["description"].strip(),
                              "cat": cats.get(r.get("food_category_id", ""), "")}
    ids = macro_ids(os.path.join(d, "nutrient.csv"))
    id2key = {v: k for k, v in ids.items()}
    for r in csv.DictReader(open(os.path.join(d, "food_nutrient.csv"), encoding="utf-8")):
        fid = r["fdc_id"]
        if fid in foods:
            k = id2key.get(r["nutrient_id"])
            if k:
                foods[fid].setdefault("n", {})[k] = num(r["amount"])
    return foods


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


def sql_lit(s):
    return "'" + s.replace("'", "''") + "'" if s else "null"


def n(v):
    return str(v) if v is not None else "null"


def emit_sql(all_foods, path):
    out = ["-- Generated by pipeline/ingest_usda.py — USDA FDC (public domain) ingredient load.",
           "-- Run AFTER schema migration + after IFCT load. Idempotent.", "begin;"]
    seen = set()
    for src, fid, f in all_foods:
        nu = f.get("n", {})
        slug = slugify(f["desc"]) or f"usda-{fid}"
        if slug in seen:
            slug = f"{slug}-{fid}"
        seen.add(slug)
        out.append(
            f"with ing as (\n"
            f"  insert into ingredients (slug, canonical_name, category)\n"
            f"  values ('{slug}', {sql_lit(f['desc'])}, {sql_lit(f['cat'])})\n"
            f"  on conflict (slug) do update set canonical_name = excluded.canonical_name returning id\n"
            f"), st as (\n"
            f"  insert into ingredient_states (ingredient_id, state) select id, 'raw' from ing\n"
            f"  on conflict (ingredient_id, state) do update set state = excluded.state returning id\n"
            f")\n"
            f"insert into nutrient_values (ingredient_state_id, source_id, source_food_code, "
            f"energy_kcal, energy_kj, protein_g, fat_g, carb_avail_g, fibre_g, water_g, provenance, confidence)\n"
            f"select st.id, '{src}', '{fid}', {n(nu.get('kcal'))}, {n(nu.get('kj'))}, "
            f"{n(nu.get('protein'))}, {n(nu.get('fat'))}, {n(nu.get('carb'))}, {n(nu.get('fibre'))}, "
            f"{n(nu.get('water'))}, 'measured', 'high' from st\n"
            f"on conflict (ingredient_state_id, source_id, version) do nothing;")
    out.append("commit;")
    open(path, "w", encoding="utf-8").write("\n".join(out))


def emit_report(app_foods, index, path):
    L = ["# USDA Coverage — gap foods IFCT could not match\n",
         "| App food | USDA match | kcal | P | F | C | Fibre |",
         "|---|---|--:|--:|--:|--:|--:|"]
    hits = 0
    for af in app_foods:
        key = af["name"].lower()
        if key in USDA_TARGETS:
            kw = USDA_TARGETS[key]
            # prefer the shortest description containing the keyword that has kcal
            # (generic "Oats" beats branded "Cereals ... POST HONEY BUNCHES ... oats")
            cands = [f for _, _, f in index
                     if kw in f["desc"].lower() and f.get("n", {}).get("kcal") is not None]
            exact = [f for f in cands if f["desc"].lower() == kw]
            wb = [f for f in cands if re.search(r"\b" + re.escape(kw) + r"\b", f["desc"].lower())]
            pool = exact or wb or cands          # exact desc > word-boundary > any substring
            m = min(pool, key=lambda f: len(f["desc"])) if pool else None
            if m:
                hits += 1
                nu = m.get("n", {})
                L.append(f"| {af['name']} | {m['desc'][:42]} | {n(nu.get('kcal'))} | "
                         f"{n(nu.get('protein'))} | {n(nu.get('fat'))} | {n(nu.get('carb'))} | {n(nu.get('fibre'))} |")
            else:
                L.append(f"| {af['name']} | (no match for '{kw}') | | | | | |")
    L.insert(1, f"\n**Gap foods resolved via USDA: {hits}/{len(USDA_TARGETS)}**\n")
    open(path, "w", encoding="utf-8").write("\n".join(L))
    return hits


def main():
    app_foods = load_app_foods()
    index = []
    counts = {}
    for d, src, dt in DATASETS:
        if not os.path.isdir(d):
            print(f"!! missing dataset dir: {d}", file=sys.stderr); continue
        foods = load_dataset(d, dt)
        counts[src] = len(foods)
        for fid, f in foods.items():
            index.append((src, fid, f))
    emit_sql(index, OUT_SQL)
    hits = emit_report(app_foods, index, OUT_RPT)
    for s, c in counts.items():
        print(f"{s:10}: {c} foods")
    print(f"total ingested: {len(index)}")
    print(f"gap foods resolved via USDA: {hits}/{len(USDA_TARGETS)}")
    print(f"SQL   -> {os.path.relpath(OUT_SQL, ROOT)}")
    print(f"report-> {os.path.relpath(OUT_RPT, ROOT)}")


if __name__ == "__main__":
    main()
