#!/usr/bin/env python3
"""Turn recipes_mapped.json into loadable SQL for recipes / recipe_ingredients /
recipe_nutrition, applying the Atwater sanity gate.

Status policy (matches the trust discussion):
  * clean (>=90% ingredients mapped AND Atwater-consistent) -> status 'draft'  (promotable)
  * flagged (low mapping or Atwater fail)                   -> status 'rejected' + flags
Method prose is intentionally NULL — facts only; the LLM rewrites methods later.
recipe_ingredients link to ingredient_state_id best-effort by exact canonical name.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "pipeline/out/recipes_mapped.json")
OUT = os.path.join(ROOT, "pipeline/out/recipes_load.sql")


# extractor confidence labels -> schema CHECK enum (high/medium/low/unmatched)
CONF_MAP = {"high(alias)": "high", "high(exact)": "high", "exact": "high",
            "medium(prefix)": "medium", "prefix": "medium",
            "low(fuzzy)": "low", "fuzzy": "low", "token": "low", "unmatched": "unmatched"}


def conf_enum(c):
    return CONF_MAP.get(c, "low")


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


def lit(s):
    return "'" + str(s).replace("'", "''") + "'" if s not in (None, "") else "null"


def n(v):
    return str(v) if v is not None else "null"


def atwater_flags(c, mapped_pct):
    flags = []
    if mapped_pct < 90:
        flags.append("low_mapping")
    if c and c.get("kcal"):
        atw = 4 * (c.get("carb") or 0) + 4 * (c.get("protein") or 0) + 9 * (c.get("fat") or 0)
        if abs(atw - c["kcal"]) > 20 and abs(atw - c["kcal"]) / c["kcal"] > 0.15:
            flags.append("atwater_fail")
    else:
        flags.append("no_nutrition")
    return flags


def main():
    recipes = json.load(open(SRC))
    out = ["-- Generated by pipeline/load_recipes.py — recipe corpus (facts only).",
           "-- Run AFTER schema + ingredient loads.", "begin;",
           "insert into sources (id,name,description,license) values "
           "('CORPUS','Indian recipe corpus (facts-derived)',"
           "'Ingredient lists + quantities only; nutrition recomputed from our tables; methods rewritten','Facts only') "
           "on conflict (id) do nothing;"]
    clean = flagged = 0
    seen = set()
    for r in recipes:
        c = r.get("computed_per100g")
        flags = atwater_flags(c, r.get("mapped_pct", 0))
        status = "draft" if not flags else "rejected"
        clean += status == "draft"; flagged += status != "draft"
        slug = slugify(r["name"]) or "recipe"
        if slug in seen:
            slug += "-" + str(len(seen))
        seen.add(slug)
        out.append(
            f"with r as (insert into recipes (slug,name,tagline,prep_mins,method,status,source_id,source_ref) "
            f"values ({lit(slug)},{lit(r['name'])},{lit(r.get('cuisine'))},"
            f"{n(int(r['time_mins']) if str(r.get('time_mins','')).isdigit() else None)},null,"
            f"{lit(status)},'CORPUS',{lit(r['name'])}) returning id)")
        if c:
            out.append(
                f"insert into recipe_nutrition (recipe_id,per,energy_kcal,protein_g,fat_g,carb_avail_g,fibre_g,flags,method_version) "
                f"select id,'per_100g',{n(c.get('kcal'))},{n(c.get('protein'))},{n(c.get('fat'))},"
                f"{n(c.get('carb'))},{n(c.get('fibre'))},"
                f"ARRAY[{','.join(lit(f) for f in flags)}]::text[],'FAO-INFOODS-v0' from r;")
        else:
            out.append("select 1;")
        for pos, ing in enumerate(r["ingredients"]):
            mk = ing.get("matched")
            link = (f"(select ist.id from ingredients i join ingredient_states ist on ist.ingredient_id=i.id "
                    f"where lower(i.canonical_name)={lit(mk)} limit 1)") if mk and mk != "(zero-cal)" else "null"
            out.append(
                f"insert into recipe_ingredients (recipe_id,ingredient_state_id,raw_text,qty,unit,grams_resolved,match_confidence,position,notes) "
                f"select id,{link},{lit(ing.get('raw'))},{n(ing.get('qty'))},{lit(ing.get('unit'))},"
                f"{n(ing.get('grams'))},{lit(conf_enum(ing.get('conf')))},{pos},{lit(mk)} from "
                f"(select id from recipes where slug={lit(slug)}) r;")
    out.append("commit;")
    open(OUT, "w").write("\n".join(out))
    print(f"recipes total : {len(recipes)}")
    print(f"  -> draft (clean, promotable): {clean}")
    print(f"  -> rejected (flagged)       : {flagged}")
    print(f"SQL -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
